version: '3.8'
services:
  web:
    image: odoo:latest
    depends_on:
      - db
    ports:
      - 8070:8069
    volumes:
      - ./module:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
secrets:
  postgresql_password:
    file: odoo_pg_pass